create table candidate
(
id INT NOT NULL AUTO_INCREMENT,
name varchar(20) NOT NULL,
address varchar(20),
dateOfBirth varchar(20),
qualification varchar(20) NOT NULL,
totalExperience int,
experience int,
noticePeriod int,
salaryExpectation float,
ableToRelocate boolean,
currentSalary float,
skills varchar(20),
gender varchar(20),
phone varchar(20) NOT NULL,
email varchar(20) NOT NULL,
isDeleted boolean,
isShortListed boolean,
create_timestamp timestamp,
update_timestamp timestamp,
uniqueId varchar(20) NOT NULL,
previousCompany varchar(20),
attemptCount int,
carrierStartDate varchar(20),
applicantType varchar(20),
postApplied varchar(20),
referalId varchar(20),
primary key(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;